import { workstationChannel, type PairingOffer } from '@inventur/shared';
import { useEffect, useState } from 'react';
import { useAction } from '../api/useAction.ts';
import { Dialog } from '../components/Dialog.tsx';
import { ErrorNotice } from '../components/Notice.tsx';
import { useRealtimeEvents } from '../realtime/RealtimeProvider.tsx';
import { useStation } from './StationContext.tsx';

/** Formats the six-digit code for reading aloud, e.g. "123 456". */
export function formatCode(code: string): string {
  return `${code.slice(0, 3)} ${code.slice(3)}`;
}

function formatRemaining(ms: number): string {
  const seconds = Math.max(0, Math.ceil(ms / 1000));
  return `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, '0')}`;
}

/** Time after a successful pairing before the dialog closes by itself. */
const CLOSE_AFTER_PAIRING_MS = 2000;

/**
 * Shows a QR code and a six-digit code with which a phone pairs with this
 * workstation. Both are valid for five minutes and only once.
 */
export function PairingDialog({ onClose }: { onClose: () => void }) {
  const { api, state } = useStation();
  const [offer, setOffer] = useState<PairingOffer>();
  const [paired, setPaired] = useState(false);
  const [now, setNow] = useState(() => Date.now());
  const create = useAction();

  async function createOffer() {
    await create.run(async () => setOffer(await api.post<PairingOffer>('/api/station/pairings')));
  }

  useEffect(() => {
    void createOffer();
    // Only once when the dialog opens.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    const timer = setInterval(() => setNow(Date.now()), 1000);
    return () => clearInterval(timer);
  }, []);

  useRealtimeEvents([workstationChannel(state.workstation.id)], (event) => {
    if (
      event.type === 'pairing.changed' &&
      event.action === 'created' &&
      event.pairingId === offer?.id
    ) {
      setPaired(true);
    }
  });

  useEffect(() => {
    if (!paired) return;
    const timer = setTimeout(onClose, CLOSE_AFTER_PAIRING_MS);
    return () => clearTimeout(timer);
  }, [paired, onClose]);

  function close() {
    // An unused offer is withdrawn, so the code cannot be used any more.
    if (offer && !paired) void api.delete(`/api/station/pairings/${offer.id}`).catch(() => {});
    onClose();
  }

  const remaining = offer ? new Date(offer.validUntil).getTime() - now : 0;
  const expired = offer !== undefined && remaining <= 0;

  return (
    <Dialog
      title="Handy koppeln"
      onClose={close}
      actions={
        <button type="button" onClick={close}>
          {paired ? 'Schließen' : 'Abbrechen'}
        </button>
      }
    >
      <ErrorNotice error={create.error} />
      {paired && (
        <div className="notice success pairing-success" role="status">
          Handy verbunden
        </div>
      )}
      {offer && !paired && (
        <div className="pairing">
          <div className="pairing-main">
            <p>Mit der Kamera des Handys diesen QR-Code scannen:</p>
            <div
              className={`qr ${expired ? 'expired' : ''}`}
              aria-label="QR-Code zum Koppeln"
              role="img"
              // The SVG is generated by our own server.
              dangerouslySetInnerHTML={{ __html: offer.qrSvg }}
            />
            <p>
              Oder auf dem Handy <strong>{offer.scanUrl}</strong> öffnen und diesen Code eingeben:
            </p>
            <p className="pairing-code" aria-label="Kopplungscode">
              {formatCode(offer.code)}
            </p>
            {expired ? (
              <p>
                Der Code ist abgelaufen.{' '}
                <button type="button" className="primary" onClick={() => void createOffer()}>
                  Neuen Code erzeugen
                </button>
              </p>
            ) : (
              <p className="muted">
                Gültig noch {formatRemaining(remaining)} Minuten, nur für ein Handy.
              </p>
            )}
          </div>
          <details className="pairing-certificate">
            <summary>Erstes Mal mit diesem Handy? Zuerst das Zertifikat installieren</summary>
            <div className="pairing-certificate-body">
              <div
                className="qr small"
                aria-label="QR-Code zur Zertifikatsinstallation"
                role="img"
                dangerouslySetInnerHTML={{ __html: offer.certificateQrSvg }}
              />
              <p>
                Diesen QR-Code scannen oder <strong>{offer.certificateUrl}</strong> öffnen, das
                Zertifikat herunterladen und der Anleitung folgen. Ohne Zertifikat zeigt das Handy
                eine Sicherheitswarnung, und die Kamera funktioniert nicht.
              </p>
            </div>
          </details>
        </div>
      )}
    </Dialog>
  );
}
